import 'package:file_export/file_export.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  const channel = MethodChannel('file-export-test');
  const exporter = FileExporter(channel: channel);
  final messenger =
      TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger;

  tearDown(() => messenger.setMockMethodCallHandler(channel, null));

  test('sends generated bytes without changing the file name', () async {
    late MethodCall call;
    messenger.setMockMethodCallHandler(channel, (value) async {
      call = value;
      return <String, Object>{
        'status': 'exported',
        'location': 'content://documents/recovery-key',
      };
    });

    final result = await exporter.exportBytes(
      fileName: 'ente_recovery_key.txt',
      mimeType: 'text/plain',
      bytes: Uint8List.fromList(<int>[1, 2, 3]),
    );

    expect(result, isA<FileExported>());
    expect(
      (result as FileExported).location,
      'content://documents/recovery-key',
    );
    expect(call.method, 'export');
    final arguments = call.arguments as Map<Object?, Object?>;
    expect(arguments['fileName'], 'ente_recovery_key.txt');
    final source = arguments['source'] as Map<Object?, Object?>;
    expect(source['type'], 'bytes');
    expect(source['bytes'], Uint8List.fromList(<int>[1, 2, 3]));
  });

  test('sends an existing path instead of loading its contents', () async {
    late MethodCall call;
    messenger.setMockMethodCallHandler(channel, (value) async {
      call = value;
      return <String, Object>{'status': 'cancelled'};
    });

    final result = await exporter.exportFile(
      fileName: 'ente-logs.zip',
      mimeType: 'application/zip',
      path: '/tmp/logs.zip',
    );

    expect(result, isA<FileExportCancelled>());
    final arguments = call.arguments as Map<Object?, Object?>;
    final source = arguments['source'] as Map<Object?, Object?>;
    expect(source, <String, Object>{'type': 'file', 'path': '/tmp/logs.zip'});
  });

  test('preserves a native failure reason', () async {
    messenger.setMockMethodCallHandler(channel, (_) async {
      return <String, Object>{
        'status': 'failed',
        'reason': 'sourceMissing',
        'message': 'Source file no longer exists',
      };
    });

    final result = await exporter.exportFile(
      fileName: 'logs.zip',
      mimeType: 'application/zip',
      path: '/tmp/logs.zip',
    );

    expect(result, isA<FileExportFailed>());
    final failure = result as FileExportFailed;
    expect(failure.reason, FileExportFailure.sourceMissing);
    expect(failure.message, 'Source file no longer exists');
  });

  test('rejects paths embedded in a suggested file name', () {
    expect(
      () => exporter.exportBytes(
        fileName: '../key.txt',
        mimeType: 'text/plain',
        bytes: Uint8List(0),
      ),
      throwsArgumentError,
    );
  });

  test('rejects malformed MIME types', () {
    expect(
      () => exporter.exportBytes(
        fileName: 'key.txt',
        mimeType: 'text',
        bytes: Uint8List(0),
      ),
      throwsArgumentError,
    );
  });
}
