name: "Build (Native components)"

on:
    pull_request:
        paths:
            - ".github/workflows/native-components.yml"
            - "android/.editorconfig"
            - "android/build.gradle.kts"
            - "android/gradle.properties"
            - "android/gradle/**"
            - "android/gradlew"
            - "android/packages/fonts/**"
            - "android/settings.gradle.kts"
    workflow_dispatch:

permissions:
    contents: read

jobs:
    android:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
            - name: Check Android fonts
              working-directory: android
              run: |
                  ./gradlew \
                    :packages:fonts:ktfmtCheck \
                    :packages:fonts:lintDebug \
                    :packages:fonts:assembleDebug \
                    :apps:ensu:app:compileDebugKotlin \
                    -x :apps:ensu:rust:buildRustJniDebug
